baseURL = 'https://cswenyuanxiao.github.io/SingleProject/'
languageCode = 'en-us'
title = 'Home'
theme = 'hugo-bootstrap-theme'
themesDir = 'node_modules/@filipecarneiro'

# 确保URL路径正确
canonifyURLs = true

[params]
description = "Interactive analysis of peer review effectiveness in computing science courses"
disqusShortname = "project-bnl3amf11h"  

  [[menu.main]]
    name = "Comparison"
    url = "/comparison/"
    weight = 1

  [[menu.main]]
    name = "Suggestions"
    url = "/suggestions/"
    weight = 3

  [[menu.main]]
    name = "Factors"
    url = "/factors/"
    weight = 2

  [[menu.main]]
    name = "Feedback"
    url = "/feedback/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 5

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 6

 
 [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow original HTML

  [security]
  [security.csp]
    script-src = ["'self'", "https://cdn.jsdelivr.net"]

  [outputs]
  home = ["HTML", "RSS", "JSON"]

 [taxonomies]
  category = "categories"
  tag = "tags"