baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Home'
theme = 'hugo-bootstrap-theme'
themesdir = 'node_modules/@filipecarneiro'



[params]
description = "Interactive analysis of peer review effectiveness in computing science courses"
disqusShortname = "project-bnl3amf11h"  

[menu]
  [[menu.main]]
    name = "Comparison"
    url = "/comparison/"
    weight = 1
  [[menu.main]]
    name = "Suggestions"
    url = "/suggestions/"
    weight = 2
 
 [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow original HTML

  [security]
  [security.csp]
    script-src = ["'self'", "https://cdn.jsdelivr.net"]

 
 