baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Peer Review Research Hub'
theme = 'hugo-bootstrap-theme'
themesdir = 'node_modules/@filipecarneiro'


[params]
description = "Interactive analysis of peer review effectiveness in computing science courses"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Comparison"
    url = "/comparison"
    weight = 2
  [[menu.main]]
    name = "Suggestions"
    url = "/suggestions"
    weight = 3