[build]
  
  publish = "public"
  
  command = "hugo --minify"

[build.environment]

  HUGO_VERSION = "0.142.0"

  HUGO_ENV = "production"
  
  NODE_VERSION = "16"
  
  # 
  HUGO_THEMESDIR = "themes"
  

# [[plugins]]
#   package = "@netlify/plugin-hugo" 